name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@8b799d4bc26a289a67edf350c83d0739018c353c
    with:
      parallel-commands: |
        npx nx workspace-lint
        npx nx format:check
      # storybook is built as part of the separate storybook.yml workflow,
      # Next.js apps are built on Vercel, so we exclude them all from the build here
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --prod --parallel=3 --exclude website,storybook

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@8b799d4bc26a289a67edf350c83d0739018c353c
    with:
      number-of-agents: 3
